#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -rf constant/polyMesh/sets

runApplication blockMesh
runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite

# Restore initial fields
restore0Dir

runApplication splitMeshRegions -cellZones -overwrite

touch jjj.foam



